# Site
title: Simple
subtitle: 简简简简单
description: JavaScript, ES6, CSS, 前端笔记
author: no-nothing
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://singple.com
root: /
# permalink: :year/:month/:day/:title/
# permalink: :category/:id
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
auto_spacing: false
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
theme: landscape

# Deployment
deploy:
  type: git
  repo:
    github: git@github.com:no-nothing/no-nothing.github.io.git
    coding: https://git.coding.net/know-nothing/know-nothing.coding.me.git
    # qcloud: git@119.29.107.78:/home/git/blog.git
  branch: master
