# Header
menu:
  首页: /
  归档: /archives
# rss: /atom.xml

# Content
excerpt_link: 查看更多
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
# - tagcloud
# - archive
- recent_posts
- friends

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
# google_analytics:
favicon: /favicon.ico
# twitter:
# google_plus:
# fb_admins:
# fb_app_id: