# Header
menu:
  首页: /
  归档: /archives
  聚合: /atom.xml

rss: /atom.xml

# Content
excerpt_link: 查看更多
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
# - tagcloud
# - archive
- recent_posts
- friends

friends:
  叶丹波: http://www.yedanbo.com/
  Kelo: https://kongwz.github.io

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
# google_analytics:
favicon: /images/favicon.ico
share_avatar: /images/avatar.jpg
# twitter:
# google_plus:
# fb_admins:
# fb_app_id:
