# Header
menu:
  首页: /
  归档: /archives

rss: /atom.xml

# Content
excerpt_link: 查看更多
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
#- tag
- tagcloud
- recent_posts
#- friends
#- archive

friends:
  叶丹波: http://www.yedanbo.com/
  Kelo: https://kongwz.github.io/
  #ivyesthan: http://ivyesthan.cn/
  Eternal: https://colorfulWorld.github.io/

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
#- category
#- tagcloud
#- archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
favicon: /images/favicon.ico
share_avatar: /images/avatar.jpg
#google_analytics:
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:
